Lambda-School-Labs/sauti-databank-be

- api/server.js
- graphQL/model.js
- graphQL/queries.js
- graphQL/schema.js
- index.js
- package-lock.json
- package.json
Build GraphQL schema on backend
> Building out schema

- api/server.js
- graphQL/model.js
- graphQL/queries.js
- graphQL/schema.js
- package-lock.json
Adjusted incorrect naming convention on schema and graphql resolvers.
> Adjustedincorrect naming conventions throughout sschema and resolvers

- models/dataCleaner.js
- models/infodemand-model.js
- models/sessionsDataParcer.js
- models/traders-model.js
Code is parsing data correctly from platform_sessions table, and using test model function to insert into the table.
> Data parsing

- CSV_files/users.csv
- dbConfig.js
- graphQL/resolvers.js
- graphQL/schema.js
- knexfile.js
- models/dataCleaner.js
- models/infodemand-model.js
- models/model.js
- models/sessions-model.js
- models/sessionsDataParser.js
- models/traders-model.js
- package-lock.json
Updated sessionsDataParser.js to copy the created_date column from platform_sessions tables in DB, into information_demand table. Eliminating the need to join the platform_sessions table at all.
> Graphql schema update

- models/model.js
Fixed the broken getUsers model that was left unusuable after fixing the getSessions model. It caused the single filtering on the front end to break, it is now resolved.
> Fixed broken getUsers model.

- graphQL/schema.js
- models/model.js
Updated model and schema to return a trader's cell number
> Updated model and schema to return a trader's cell number

- graphQL/schema.js
- server.js
Added a duplicate of tradersData schema to support additionalFilterData.
> Added a duplicate of tradersData schema to support additionalFilterData.

- graphQL/schema.js
Added additional_filter_type to schema so that queries support having multiple request_type arguments
> added schema options for additional filter as a second request_type

- helloWorld.js
- models/model.js
- models/sessionsDataParser.js
- package-lock.json
- package.json
- server.js
24 hour update using heroku scheduler
> Cron feature

- helloWorld.js
- index.js
- models/cronTest.js
Removed remnants of cron testing files.
> Removed remnants of cron testing files.

- graphQL/resolvers.js
- graphQL/schema.js
- knexfile.js
- models/model.js
- models/sessionsDataParser.js
- server.js
Updated the sessionsDataParser.js to insert every request_type as it's own column in the new table, parsed_data. Implemented the appropriate knex model functions to return a joined master table between the 'traders' and 'parsed_data' table. Added 'TraderSession' graphQL 'type' to allow querying of data from new 'parsed_data' table.
> Data parsing refactor

- index.js
- models/tradersDataParser.js
Commented parsing files so it is clear how they are working, when they run, and which versions are currently in use VS. which are going to be used for future releases.
> Commented model and parsing files.

- package.json
Removed unused scripts in package.json
> Removed unused scripts in package.json

- package.json
> Removed typo in package.json

- graphQL/resolvers.js
- models/model.js
Removed broken export statements for removed functions.
> Removed export statements for removed functions.

- graphQL/resolvers.js
- graphQL/schema.js
- index.js
- package-lock.json
- package.json
- server.js
> convert to apollo-server from express

- .gitattributes
- .prettierrc.json
- package-lock.json
- package.json
I configured Prettier to the agreed upon settings.
> Configure prettier

- graphQL/resolvers.js
- server.js
> cors added

- server.js
> David apollo

- package-lock.json
> sauti sserver

- graphQL/resolvers.js
> Resolver auth

- graphQL/resolvers.js
> remove the "password" field from the response in the login resolver

- graphQL/resolvers.js
- graphQL/schema.js
Fixes #56 
- [] Complete, tested, ready to review and merge
> Make user's tier an enumerated value

- graphQL/resolvers.js
- graphQL/schema.js
> Return a helpful error message when attempting to register an existing user.

- graphQL/resolvers.js
- graphQL/schema.js
- package-lock.json
- server.js
Add an enumerated value for a new field in the schema called "organization_type". The enumerated values are "GOVERNMENT, "NGO", "RESEARCHER, and "OTHER".
> Add organization type enum

- graphQL/resolvers.js
- graphQL/schema.js
- index.js
- models/databankUsers.js
- package.json
- server.js
> Fix edit and delete user bugs

- graphQL/schema.js
Rename one of the enum fields on OrganizationType. The field "RESEARCHER" was changed to "RESEARCH"
> rename a field on the OrganizationType enum 

- graphQL/resolvers.js
- graphQL/schema.js
Co-authored-by: Lukas <jaronisluke13@gmail.com>
Co-authored-by: Joshua Hill <Josh_Hill15@me.com>
Co-authored-by: David Tauraso <david318@me.com>
> fix bug where user tier wasn't showing up on the token

- graphQL/resolvers.js
> factor graphql to work with paypal

- graphQL/resolvers.js
> register now returns a token

- graphQL/resolvers.js
- graphQL/schema.js
- package-lock.json
- package.json
> Paypal stuff

- graphQL/resolvers.js
> tweak resolvers

- graphQL/resolvers.js
- graphQL/schema.js
Co-authored-by: Vincent Pagano <vpagano10@gmail.com>
> revise suspension to cancel. Successful cancellation eliminates subscription_id; sets tier to free.

- graphQL/resolvers.js
> update resolvers for paypal

- graphQL/resolvers.js
- graphQL/schema.js
> added addplan mutation

- config/secrets.js
- graphQL/resolvers.js
> Paypal update

- models/paypalCancellation.js
The "cron" package isn't being used anymore.
> remove unused import

- models/model.js
> model.js add .orderBy to getDataSessions

- config/secrets.js
- graphQL/resolvers.js
- graphQL/schema.js
- package-lock.json
- package.json
- services/EmailService.js
> Reset Password Backend Done

- services/EmailService.js
> Updated email-service-cred

- graphQL/resolvers.js
> updated URL link

- knexfile.js
- models/model.js
> Connected to sauti database

- models/tradersDataParser.js
see trello card:
https://trello.com/c/T0SINjex
Database did not take into account, trader profile information that was not submitted in English
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, tested, ready to review and merge
- [ x] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [ x] My changes generate no new warnings
- [x ] There are no merge conflicts
> add translations to tradersDataParser.js

- models/sessionsDataParser.js
Removed erroneous data from MySQL
https://trello.com/c/cVrRjL8d
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] Complete, tested, ready to review and merge
- [ x ] I have performed a self-review of my own code
- [ x ] My code has been reviewed by at least one peer
- [ x ] I have commented  my code, particularly in hard-to-understand areas
- [ x ] My changes generate no new warnings
- [ x ] There are no merge conflicts
> Remove numbers

- README.md
- models/dataNormalize.js
- models/sessionsDataParser.js
The file `dataNormalize.js` in the `models` folder is a function that takes in the cleaned data and removes several issues that caused duplicate or confusing data to return such as:
-- Multiple entries due to captialization,
-- Multiple entries due to the word "Market" being included in some entries and not others,
-- Translates several words including Ibishyimbo => Beans, Mpunga => Rice, Nguo	=> Clothing, Nyanya => Tomato, Umuceri =>	rice.
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] This change requires a documentation update
- [X ] Complete, tested, ready to review and merge
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] My code has …
> Data normalize

- models/dictionary.js
- models/dictionaryParcer.js
- models/sessionsDataParser.js
- models/tests/dictionaryParcer.test.js
- models/tests/seperateMultiples.test.js
- models/tests/testDummyData.js
Created test files to check data parsing functions including DictionaryParse and SeparateMultiples parsers. These tests check if output of data after being parsed matches expectations.
We also made a minor change in the data that removes excess markets being displayed in procedure destination and exchange direction.
> Created Dictionary Parser tests and fixed minor data bug

- models/tests/seperateMultiples.test.js
- models/tests/testDummyData.js
Fixes small issue where tests do not look for array lengths over 2. Test still needs update to work with multiples of same data. 
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Complete, tested, ready to review and merged
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] My code has been reviewed by at least one peer
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] There are no merge conflicts
> minor fix so that the tests catch array lengths of over 3

- models/tradersDataParser.js
added a translation for Females from Rwanda
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] There are no merge conflicts
> female=Gore

- models/dictionary.js
- models/dictionaryParcer.js
Removes unnecessary values from database. 
> fixed random values being passed through proceduredest

- models/sessionsDataParser.js
fixes an issue with filtering out numbers for the commodity Market
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Complete, tested, ready to review and merge
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] My code has been reviewed by at least one peer
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] There are no merge conflicts
> Added filter for commodityMarket to filter out numbers and odd values

- README.md
- graphQL/schema.js
- models/model.js
- models/tradersDataParser.js
Add crossing location to tradersUsers.js
Add Rwanda Translations to tradersUsers.js
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, tested, ready to review and merge
- [ x] I have performed a self-review of my own code
> Crossing location
